#!/usr/bin/env python3
"""Generate web/emoji.js — the emoji picker data — from Unicode's
emoji-test.txt, the machine-readable form of the full emoji list
(https://www.unicode.org/emoji/charts/full-emoji-list.html).

Run manually when bumping to a new Unicode/emoji version:

    python3 tools/emoji.py                      # download + generate
    python3 tools/emoji.py emoji-test.txt       # from a local copy

Output is committed (web/emoji.js); the binary embeds it at build time.
Only fully-qualified emojis are kept; the Component group (skin tones,
ZWJ building blocks) drops out on its own. The name that follows the
emoji in each entry powers search and button tooltips.
"""

import json
import re
import sys
import urllib.request

URL = "https://unicode.org/Public/emoji/latest/emoji-test.txt"
CODEPOINTS = re.compile(r"^[0-9A-Fa-f]{1,8}( [0-9A-Fa-f]{1,8})* *$")


def parse(text):
    """Return (version, [(group, [(emoji, name), ...]), ...]) keeping only
    fully-qualified entries. Lines look like:

        1F600                          ; fully-qualified     # 😀 E1.0 grinning face
    """
    version, groups, current = "", [], None
    for line in text.splitlines():
        if line.startswith("# Version:"):
            version = line.split(":", 1)[1].strip()
        elif line.startswith("# group:"):
            current = []
            groups.append((line.split(":", 1)[1].strip(), current))
        elif line.startswith("#") or not line.strip():
            continue
        elif current is not None:
            codepoints, _, rest = line.partition(";")
            if not CODEPOINTS.match(codepoints.strip() + " "):
                continue
            status = rest.split("#", 1)[0].strip()
            comment = rest.split("#", 1)[1].split() if "#" in rest else []
            if status != "fully-qualified" or len(comment) < 3:
                continue
            current.append((comment[0], " ".join(comment[2:])))
    return version, [(name, items) for name, items in groups if items]


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else URL
    text = urllib.request.urlopen(src).read().decode() if src.startswith("http") \
        else open(src, encoding="utf-8").read()
    version, groups = parse(text)
    n = sum(len(items) for _, items in groups)
    out = sys.argv[2] if len(sys.argv) > 2 else "web/emoji.js"
    with open(out, "w", encoding="utf-8") as f:
        f.write("// web/emoji.js — emoji picker data, GENERATED by tools/emoji.py\n")
        f.write(f"// from Unicode emoji-test.txt v{version} ({n} fully-qualified emojis). Do not edit.\n")
        f.write(f"const EMOJI_VERSION = {json.dumps(version)};\n")
        f.write("// [group, [[emoji, name], ...]] in chart order\n")
        f.write("const EMOJI_GROUPS = ")
        f.write(json.dumps(groups, ensure_ascii=False, separators=(",", ":")))
        f.write(";\n")
    print(f"{out}: v{version}, {n} emojis in {len(groups)} groups")


if __name__ == "__main__":
    main()
